### ISSUE TITLE
how can I help?  What's the future of List Hero?

### ISSUE THREAD

**Issue by bnfinet** [flash1293/ekofe#157]
Thank you for making List Hero!  My wife and I have started to use it for our shopping list.  I've looked far and wide for something like List Hero and I'm quite impressed.  We have very quickly migrated to ListHero from Plant To Eat.  List Hero is much faster and much more intuitive.

Looks like the cert expired a few hours ago...

```
listhero.de uses an invalid security certificate. The certificate expired on April 10, 2019, 7:03:37 AM GMT-7. The current time is April 10, 2019, 11:47 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE
```

I'd like to offer suggestions and possibly contribute code to List Hero.  Are you looking to grow the project?  Are you open to suggestions and ideas?

Thanks again!

**Comment by bnfinet** [comment]
@flash1293 looks it's fixed!  hurrah!  I'll change the issue title to reflect my other question

**Comment by flash1293** [comment]
Hi @bnfinet, it's really nice to hear that there are people using Listhero. I'm using it myself for keeping track of shopping lists and todo lists so it definitely won't go away.

In the last few months I didn't really have the time to continue development, but I'm definitely open to free up a few hours per month especially if there are other people using the service :) The features and improvements I was planning to work on are all kept in the issues of this repository, but I'm definitely open to suggestions - feel free to open your own issues to start discussion. I you can help out with code too, I'm very happy to do reviews.

**Comment by bnfinet** [comment]
Thanks so much @flash1293 , I'll look at the existing issues and post a few too
