### ISSUE TITLE
change Last Recently Used to something else

### ISSUE THREAD

**Issue by bnfinet** [flash1293/ekofe#159]
I know what LRU is but my wife is confused by the term :)

How about
 * Completed Items
 * Recent Items
 * Done
 * Finished

**Comment by flash1293** [comment]
Thanks for the hint. I changed it to "Recent Entries" for now because most parts of the app use that terminology.

I have a feeling that item might be better though, I will clean that up in https://github.com/flash1293/ekofe/issues/163

What do you think?
