### ISSUE TITLE
add timestamps for created and last marked done for each item on Last Recently Used

### ISSUE THREAD

**Issue by bnfinet** [flash1293/ekofe#161]
But only if it doesn't look cluttered.  I love how simple the whole app is.

**Comment by flash1293** [comment]
This is basically an extension of https://github.com/flash1293/ekofe/issues/115, I will close it there and continue discussion here.

I'm totally on board with adding the "last marked done" timestamp, but I'm not sure about "created". What specific use case do you have in mind? Is https://github.com/flash1293/ekofe/issues/160 solving the same / a similar problem? Maybe the log view should be filterable by event type - then it's more of an expert feature and doesn't clutter the LRU view.

**Comment by bnfinet** [comment]
Sorry to have missed #115

Yeah, created could come from #160.  I like the filter idea.  That would give a powerful historic perspective.

**Comment by flash1293** [comment]
Closing in favor of #160
