### ISSUE TITLE
Not full width on desktop

### ISSUE THREAD

**Issue by crymis** [flash1293/ekofe#79]
Even though it is a mobile-first app, i can imagine planning my shopping list at home at the desktop.

Hitting the action buttons (edit, add) seems to be uncomfortable in the corners (long mouse movements).

Just make the main window width 1/3 of the width and center it.
Adding shadow and a little darker background to present the app as a component ;)

![ekofe flash1293 de_](https://user-images.githubusercontent.com/3726683/34653438-258700f2-f3ec-11e7-8426-2ddcd39160ee.png)

**Comment by flash1293** [comment]
Which browser is this? Firefox, Safari and Chrome on MacOS work fine
<img width="1680" alt="screen shot 2018-01-07 at 8 52 11 pm" src="https://user-images.githubusercontent.com/1508364/34653498-b7571ea4-f3ec-11e7-8404-53a416b060a7.png">

**Comment by flash1293** [comment]
Mitigated in new version
